apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Architecture
  description: The Architecture department
spec:
  type: department
  profile:
    displayName: Architecture
  # Intentional no profile for testing
  children: [Background, Squads, Devops]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: raphael.riscado
spec:
  profile:
    displayName: Raphael Riscado
    email: raphael.riscado@example.com
    picture: https://avatars.dicebear.com/api/male/raphael.riscado.svg
  memberOf: [Architecture]