apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: The Architecture department
spec:
  type: department
  # Intentional no profile for testing
  parent: majdalani-company
  children: [background, squads]