apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Architecture
  description: The Architecture department
spec:
  type: department
  # Intentional no profile for testing
  children: [Background, Squads]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: raphael.riscado
spec:
  profile:
    displayName: Raphael Riscado
    email: raphael.riscado@example.com
    picture: https://avatars.dicebear.com/api/male/raphael.riscado.svg
  memberOf: [Architecture]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-groups
  description: A collection of all groups from Architecture Team
spec:
  targets:
    - ./background-group.yaml
    - ./squads-group.yaml